# contains config variables
DEFAULT_IMAGE_PATH = "./image/_raw/oscar_wilde_1.jpg"

CONVERSION_ARG_BW = 1
CONVERSION_ARG_BIN = 2

MORPH_ARG_ERODE = 1
MORPH_ARG_DILATE = 2
MORPH_ARG_OPEN = 3
MORPH_ARG_CLOSE = 4