# contains config variables
DEFAULT_IMAGE_PATH = "./image/_raw/oscar_wilde_1.jpg"

CONVERSION_ARG_BW = 0
CONVERSION_ARG_BIN = 1

MORPH_ARG_ERODE = 0
MORPH_ARG_DILATE = 1
MORPH_ARG_OPEN = 2
MORPH_ARG_CLOSE = 3